### ISSUE TITLE
Compatibility with stylelint >=19.8.2

### ISSUE THREAD

**Issue by wisko** [bjankord/stylelint-config-sass-guidelines#353] opened 2024-08-29 07:53 UTC
Stylelint made some changes in v19.8.2 (https://stylelint.io/changelog/#1682) with `content.fix` that causes errors when I try to run stylelint while using `"extends": "stylelint-config-sass-guidelines"`.

**Comment by bjankord** [comment] 2024-08-29 19:25
What does your stylelint config look like where you are getting errors?
What are the errors you are getting.

Looking for steps to reproduce so I can look into it.

**Comment by hatemhosny** [comment] 2024-09-07 04:03
This is an [example output](https://github.com/hatemhosny/racing-bars/actions/runs/10748298498/job/29811835346#step:6:83):

```
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-bang-space-after" instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-bang-space-before" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-colon-space-after" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-colon-space-before" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/function-comma-space-after" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/no-missing-end-of-source-newline" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-bang-space-after" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-bang-space-before" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-colon-space-after" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-colon-space-before" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/function-comma-space-after" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/no-missing-end-of-source-newline" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-bang-space-after" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-bang-space-before" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-colon-space-after" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/declaration-colon-space-before" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/function-comma-space-after" instead.
(node:2415) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/no-missing-end-of-source-newline" instead.
```

[versions](https://github.com/hatemhosny/racing-bars/blob/b01eeac1dec7a46a40d29b1648882b4c0f8d4a6b/package.json#L88-L89)
stylelint: "16.8.2"
stylelint-config-sass-guidelines: "12.0.0"

[.stylelintrc.json](https://github.com/hatemhosny/racing-bars/blob/develop/.stylelintrc.json)
```json
{
  "extends": "stylelint-config-sass-guidelines",
  "rules": {
    "color-named": null,
    "max-nesting-depth": 4,
    "selector-class-pattern": null,
    "selector-max-compound-selectors": 5,
    "selector-max-id": 3,
    "selector-no-qualifying-type": null
  },
  "ignoreFiles": ["**/build/**/*"]
}
```

[run command](https://github.com/hatemhosny/racing-bars/blob/b01eeac1dec7a46a40d29b1648882b4c0f8d4a6b/package.json#L41C24-L41C57)
```bash
npx stylelint "src/**/*.{css,scss}"
```

I believe this is because `@stylistic/stylelint-plugin` used the deprecated `content.fix` which has now [been fixed](https://github.com/stylelint-stylistic/stylelint-stylistic/pull/37) in the new release. So I think upgrading `@stylistic/stylelint-plugin` could potentially fix this.

**Comment by Gruven** [comment] 2024-09-09 09:11
@bjankord I think it fixed now. Could you publish new version and close this issue, please?

**Comment by jogerj** [comment] 2024-09-12 17:42
Workaround until new release in `package.json`:
```json
  "overrides": {
    "stylelint-config-sass-guidelines": {
      "@stylistic/stylelint-plugin": "^3.0.1"
    }
  }
```

**Comment by bjankord** [comment] 2024-09-14 14:20
v12.1.0 has been released and should resolve the unexpected `context.fix is being deprecated` output.
* [CHANGELOG for v12.1.0]( https://github.com/bjankord/stylelint-config-sass-guidelines/blob/main/CHANGELOG.md#1210)

Thanks for logging the issue and providing details :+1:

**Closed by bjankord** 2024-09-14 14:20 UTC
